### ISSUE TITLE
Extent Logger Funcationality Failing After Updating Java From 1.7 to 1.8

### ISSUE THREAD

**Issue by jsudhi** [anshooarora/extentreports#323]
Hello,

Till yesterday, the Extent Reports and Logging were working fine. After I updated Java from 7 to 8, I started getting run time error as below. If I comment the Extent Logger calls, it works fine again. Have I missed anything or I need to do anything extra for Extent to work with Java 8 ?

`
java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.apache.xerces.parsers.AbstractDOMParser.startDocument(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.startDocument(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl.startEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.startDocumentParsing(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at com.relevantcodes.extentreports.Configuration.getConfigurationMap(Configuration.java:38)
	at com.relevantcodes.extentreports.Report.loadConfig(Report.java:218)
	at com.relevantcodes.extentreports.ExtentReports.loadConfig(ExtentReports.java:271)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:80)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:124)
	at com.oracle.qa.reporting.ReportFactory.getExtentReport(ReportFactory.java:51)
	at com.oracle.qa.reporting.ReportFactory.getTest(ReportFactory.java:82)
	at com.oracle.qa.uitests.CommonTest.beforeMethod(CommonTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:585)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 45 more
`

**Comment by testphreak** [comment]
That's odd. No issue with ExtentReports using Java 8 here. I'm on java version 1.8.0_25. Might want to check these lines again in your project for clues.

```
com.oracle.qa.reporting.ReportFactory.getExtentReport(ReportFactory.java:51) at 
```
```
com.oracle.qa.reporting.ReportFactory.getTest(ReportFactory.java:82) at 
```
```
com.oracle.qa.uitests.CommonTest.beforeMethod(CommonTest.java:33)
```

**Comment by anshooarora** [comment]
If you have recently upgraded from Java 7 to 8, this might happen but a rebuild of your project should ideally fix such issues.
